import {
  airflowProjectText,
  aldoProjectText,
  astroLightProjectText,
  centechProjectText,
  cominityProjectText,
  defenderProjectText,
  leWagonProjectText,
  shareInProjectText,
  skeepersProjectText,
  suiToolingProjectText,
  toolyProjectText,
} from "./projectText";

const createProject = ({
  id,
  image,
  imageAlt,
  isFeatured = false,
  mediaScale = 1,
  primaryHref,
  primaryLabel,
  side,
  sourceHref,
  techStack,
  text,
  title,
}) => ({
  id,
  image,
  imageAlt,
  isFeatured,
  mediaScale,
  primaryHref,
  primaryLabel,
  side,
  sourceHref,
  techStack,
  text,
  title,
});

export const projectCatalog = [
  createProject({
    id: "suiTooling",
    image: "/static/images/suiTooling.svg",
    imageAlt: "Sui tooling project preview",
    isFeatured: true,
    mediaScale: 0.9,
    primaryHref: "https://www.sui.io/",
    primaryLabel: "View ecosystem",
    side: "left",
    sourceHref: "https://github.com/OpenZeppelin/openzeppelin-sui-marketplace",
    techStack: [
      "TypeScript",
      "Move",
      "React",
      "Sui",
      "Smart Contracts",
      "Deployment Tooling",
      "Artifacts",
      "Contract Calls",
      "Test Harness",
      "Developer Experience",
    ],
    text: suiToolingProjectText,
    title: "Sui Marketplace Tooling",
  }),
  createProject({
    id: "defender",
    image: "/static/images/defender.png",
    imageAlt: "OpenZeppelin Defender preview",
    isFeatured: true,
    primaryHref: "https://docs.openzeppelin.com/defender",
    primaryLabel: "View docs",
    side: "right",
    techStack: [
      "TypeScript",
      "Node.js",
      "Svelte",
      "AWS Lambda",
      "DynamoDB",
      "SNS",
      "SQS",
      "Microservices",
      "Automation",
      "Monitoring",
      "Smart Contracts",
      "Blockchain",
    ],
    text: defenderProjectText,
    title: "OpenZeppelin Defender",
  }),
  createProject({
    id: "astroLight",
    image: "/static/images/astroLight.svg",
    imageAlt: "Astro Light dApp preview",
    isFeatured: true,
    side: "left",
    sourceHref: "https://github.com/CoveMB/solidity-DEFI-DAO",
    techStack: [
      "Solidity",
      "Ethereum",
      "Smart Contracts",
      "DeFi",
      "DAO",
      "Governance",
      "Staking",
      "Token Swap",
      "Teaching dApp",
      "Testnet",
    ],
    text: astroLightProjectText,
    title: "Astro Light",
  }),
  createProject({
    id: "aldo",
    image: "/static/images/aldo.png",
    imageAlt: "Aldo OMS platform preview",
    isFeatured: true,
    primaryHref: "https://www.aldogroup.com/",
    primaryLabel: "Company site",
    side: "right",
    techStack: [
      "TypeScript",
      "Functional",
      "AWS Lambda",
      "DynamoDB",
      "SNS",
      "SQS",
      "EventBridge",
      "Microservices",
      "Event-Driven",
      "CI/CD",
      "CLI Tooling",
      "IDE Extension",
      "Scrum",
    ],
    text: aldoProjectText,
    title: "Aldo OMS Modernization",
  }),
  createProject({
    id: "skeepers",
    image: "/static/images/skeepers.svg",
    imageAlt: "Skeepers platform preview",
    mediaScale: 0.9,
    primaryHref: "https://skeepers.io/en/live-shopping/",
    primaryLabel: "Visit site",
    side: "left",
    techStack: [
      "TypeScript",
      "JavaScript",
      "Koa",
      "Express",
      "WebSockets",
      "Docker",
      "Terraform",
      "AWS",
      "CLI Tooling",
      "CI/CD",
      "Scrum",
      "Leadership",
    ],
    text: skeepersProjectText,
    title: "Skeepers",
  }),
  createProject({
    id: "tooly",
    image: "/static/images/tooly.png",
    imageAlt: "Tooly product preview",
    mediaScale: 1.04,
    primaryHref: "https://www.nextcanada.com/next-ai/",
    primaryLabel: "Visit program",
    side: "right",
    techStack: [
      "TypeScript",
      "Node.js",
      "Koa",
      "React",
      "GraphQL",
      "Machine Learning",
      "Architecture",
      "Product",
      "Docker",
      "Next AI",
    ],
    text: toolyProjectText,
    title: "Tooly",
  }),
  createProject({
    id: "cominity",
    image: "/static/images/cominity.png",
    imageAlt: "Cominity project preview",
    mediaScale: 0.9,
    primaryHref: "https://cominity.ca/",
    primaryLabel: "Visit site",
    side: "left",
    techStack: [
      "Docker",
      "Kubernetes",
      "AWS",
      "Serverless",
      "Lambda",
      "CI/CD",
      "DevOps",
      "Agency Delivery",
      "Mentoring",
    ],
    text: cominityProjectText,
    title: "Cominity",
  }),
  createProject({
    id: "centech",
    image: "/static/images/centech.png",
    imageAlt: "VizzMD MVP preview",
    side: "right",
    sourceHref: "https://github.com/CoveMB/Rails-React-VizzMD-App",
    techStack: [
      "Rails",
      "React",
      "MVP",
      "Product",
      "CRM",
      "Healthcare",
      "Data Visualization",
      "Startup",
    ],
    text: centechProjectText,
    title: "VizzMD",
  }),
  createProject({
    id: "leWagon",
    image: "/static/images/leWagon.png",
    imageAlt: "Le Wagon teaching preview",
    mediaScale: 0.9,
    primaryHref: "https://www.lewagon.com/",
    primaryLabel: "Visit site",
    side: "left",
    techStack: [
      "JavaScript",
      "Teaching",
      "Mentoring",
      "Full-Stack",
      "Curriculum",
      "Public Speaking",
    ],
    text: leWagonProjectText,
    title: "Le Wagon",
  }),
  createProject({
    id: "shareIn",
    image: "/static/images/shareIn.png",
    imageAlt: "Share In app preview",
    side: "right",
    sourceHref: "https://github.com/CoveMB/Rails-Share-in-App",
    techStack: [
      "Rails",
      "JavaScript",
      "WebSockets",
      "Real-Time Chat",
      "Team Project",
      "MVP",
      "Full-Stack",
    ],
    text: shareInProjectText,
    title: "Share In",
  }),
  createProject({
    id: "airflow",
    image: "/static/images/airflow.png",
    imageAlt: "Airflow reporting pipeline preview",
    mediaScale: 0.84,
    side: "left",
    sourceHref: "https://github.com/CoveMB/Python-AirflowReportPipeline",
    techStack: [
      "Python",
      "Airflow",
      "BigQuery",
      "Pandas",
      "APIs",
      "Docker",
      "Docker Compose",
      "Reporting",
    ],
    text: airflowProjectText,
    title: "Airflow Reporting Pipeline",
  }),
];

export const featuredProjects = projectCatalog.filter(
  ({ isFeatured }) => isFeatured,
);

export const archivedProjects = projectCatalog.filter(
  ({ isFeatured }) => !isFeatured,
);
