FROM node:22-slim

ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOST=0.0.0.0

RUN apt update && \
  apt-get install --no-install-recommends -y \
  libgl1-mesa-dev \
  libxi6 \
  libgconf-2-4 && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /node/app

COPY --chown=node:node package*.json yarn.lock* ./
RUN chown -R node:node .

USER node

RUN yarn install && yarn cache clean
RUN npm config set scripts-prepend-node-path true

COPY --chown=node:node . .

CMD ["yarn", "dev"]
