FROM node:13-slim

# Set environnement to development
ENV NODE_ENV=development

RUN apt update && \
  apt-get install --no-install-recommends -y \
  libgl1-mesa-dev \
  libxi6 \
  libgconf-2-4

# Change for app directory
WORKDIR /node/app

# Copy npm dependencies
COPY --chown=node:node package*.json yarn.lock* ./

# Create app directory to contain the app and set permission for node user
RUN chown -R node:node .

# Change the user to be node
USER node

# Install dependencies
RUN yarn install && yarn cache clean

# Add to PATH
RUN npm config set scripts-prepend-node-path true

# Copy existing local files into container, and set permission to node user
COPY --chown=node:node  . .

# For client frameworks in development
ENV HOST 0.0.0.0

# Use your dev command described in package.json
CMD [ "yarn", "dev"]

